FROM node:26-alpine
COPY  . /opt
WORKDIR  /opt
RUN  npm install && \
     npm run build && \ 
     apk add apache2 && \
     cp -rf dist/* /var/www/localhost/htdocs/
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
