FROM  maven:3.9.6-eclipse-temurin-17
COPY  . /opt
WORKDIR  /opt
RUN   mvn clean package -DskipTests
EXPOSE 8080
WORKDIR /opt/target
CMD ["java", "-jar", "stuent-registration-baceknd-0.0.1-SNAPSHOT.jar"]
