FROM  maven:3.9.6-eclipse-temurin-21
COPY  . /opt
WORKDIR  /opt
RUN   mvn clean package -DskipTests
EXPOSE 80
WORKDIR /opt/target
CMD ["java", "-jar", "student-registration-baceknd-0.0.1-SNAPSHOT.jar"]
